### ISSUE TITLE
Fix commerce products

### ISSUE THREAD

**Issue by jrhodes-sitback** [Sitback/presto#128]
Currently when you install Presto you can't edit product variants or add them to the cart. This is an issue with the field storage and form settings. It was previously working.

Also, when adding a product to the cart the amount is incrementing by 0.01 each time. Correct this to increment by whole numbers.

**Comment by deneus** [comment]
We create an issue ourselves here.
It seems that the $configuration have changed from 8.2.3 to 8.3.3
8.2.3: $configuration['third_party_settings']
8.3.3: $configuration['settings']['third_party_settings']

Because if we install drupal_commerce on fresh install, the default product has inline_entity_form_complex configuration working.
I was investigating why it's working on a fresh install a not with Presto anymore.

At this point, I need to test with Drupal 8.3.3 and 8.3.2 to see if we need to add a dependencie to composer.json (line 52)
